#!/bin/bash

# BOMB SCRIPT FOR UNDEFINED VAR OR ERR DURING EXECUTION
set -ue

 # VARIABLE $1 IS DATE TIME (EX: 2023-01-03 15:44:51), FROM REDIS AS LAST LINE PARSED
 # VARIABLE $2 IS FILE PATH
awk -v last_line="$1" '$0 ~ last_line{y=1;next}y' "$2"